var express = require('express');
var router = express.Router();

var taskListAll = [
  {
    id: "7887",
    mode: "默认模式",
    progress: "99%",
    target: "https://www.baidu.com",
    type: "域名任务",
    createTime: "2016-05-01",
    stopTime: "2016-06-01",
    requestNum: "88",
    scanedNum: "66",
    uid: "24",
    userName: "李铁柱",
    highNum: "6",
    midNum: "7",
    lowNum: "8",
    riskNum: "9",
    status: "运行中"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "13%",
    target: "https://www.wooyun.org https://www.qq.com https://www.weibo.com https://www.tangscan.com https://www.sangebaimao.com",
    type: "多域名任务",
    createTime: "2016-05-11",
    stopTime: "2016-06-21",
    requestNum: "99",
    scanedNum: "44",
    uid: "11",
    userName: "卡卡西",
    highNum: "16",
    midNum: "20",
    lowNum: "60",
    riskNum: "11",
    status: "已结束"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "99%",
    target: "https://www.baidu.com",
    type: "域名任务",
    highNum: "6",
    midNum: "7",
    lowNum: "8",
    riskNum: "9",
    createTime: "2016-05-01",
    stopTime: "2016-06-01",
    requestNum: "88",
    scanedNum: "66",
    uid: "24",
    userName: "李铁柱",
    status: "运行中"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "13%",
    target: "https://www.wooyun.org https://www.qq.com https://www.weibo.com https://www.tangscan.com https://www.sangebaimao.com",
    type: "多域名任务",
    highNum: "16",
    midNum: "20",
    lowNum: "60",
    riskNum: "11",
    createTime: "2016-05-11",
    stopTime: "2016-06-21",
    requestNum: "99",
    scanedNum: "44",
    uid: "11",
    userName: "卡卡西",
    status: "已结束"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "99%",
    target: "https://www.baidu.com",
    type: "域名任务",
    highNum: "6",
    midNum: "7",
    lowNum: "8",
    riskNum: "9",
    createTime: "2016-05-01",
    stopTime: "2016-06-01",
    requestNum: "88",
    scanedNum: "66",
    uid: "24",
    userName: "李铁柱",
    status: "运行中"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "13%",
    target: "https://www.wooyun.org https://www.qq.com https://www.weibo.com https://www.tangscan.com https://www.sangebaimao.com",
    type: "多域名任务",
    highNum: "16",
    midNum: "20",
    lowNum: "60",
    riskNum: "11",
    createTime: "2016-05-11",
    stopTime: "2016-06-21",
    requestNum: "99",
    scanedNum: "44",
    uid: "11",
    userName: "卡卡西",
    status: "已结束"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "99%",
    target: "https://www.baidu.com",
    type: "域名任务",
    highNum: "6",
    midNum: "7",
    lowNum: "8",
    riskNum: "9",
    createTime: "2016-05-01",
    stopTime: "2016-06-01",
    requestNum: "88",
    scanedNum: "66",
    uid: "24",
    userName: "李铁柱",
    status: "运行中"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "13%",
    target: "https://www.wooyun.org https://www.qq.com https://www.weibo.com https://www.tangscan.com https://www.sangebaimao.com",
    type: "多域名任务",
    highNum: "16",
    midNum: "20",
    lowNum: "60",
    riskNum: "11",
    createTime: "2016-05-11",
    stopTime: "2016-06-21",
    requestNum: "99",
    scanedNum: "44",
    uid: "11",
    userName: "卡卡西",
    status: "已结束"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "99%",
    target: "https://www.baidu.com",
    type: "域名任务",
    highNum: "6",
    midNum: "7",
    lowNum: "8",
    riskNum: "9",
    createTime: "2016-05-01",
    stopTime: "2016-06-01",
    requestNum: "88",
    scanedNum: "66",
    uid: "24",
    userName: "李铁柱",
    status: "运行中"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "13%",
    target: "https://www.wooyun.org https://www.qq.com https://www.weibo.com https://www.tangscan.com https://www.sangebaimao.com",
    type: "多域名任务",
    highNum: "16",
    midNum: "20",
    lowNum: "60",
    riskNum: "11",
    createTime: "2016-05-11",
    stopTime: "2016-06-21",
    requestNum: "99",
    scanedNum: "44",
    uid: "11",
    userName: "卡卡西",
    status: "已结束"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "99%",
    target: "https://www.baidu.com",
    type: "域名任务",
    highNum: "6",
    midNum: "7",
    lowNum: "8",
    riskNum: "9",
    createTime: "2016-05-01",
    stopTime: "2016-06-01",
    requestNum: "88",
    scanedNum: "66",
    uid: "24",
    userName: "李铁柱",
    status: "运行中"
  },{
    id: "7887",
    mode: "默认模式",
    progress: "13%",
    target: "https://www.wooyun.org https://www.qq.com https://www.weibo.com https://www.tangscan.com https://www.sangebaimao.com",
    type: "多域名任务",
    highNum: "16",
    midNum: "20",
    lowNum: "60",
    riskNum: "11",
    createTime: "2016-05-11",
    stopTime: "2016-06-21",
    requestNum: "99",
    scanedNum: "44",
    uid: "11",
    userName: "卡卡西",
    status: "已结束"
  }
]

router.get('/', function(req, res, next) {
  res.json(taskListAll);
});

module.exports = router;
